### ISSUE TITLE
bug with startup.S

### ISSUE THREAD

**Issue by skoppula** [MITEVT/lpc11cx4-library#1]
[this issue is based on compilation issues I was working with @agustinr19  to solve]

If you take a look at:
https://github.com/MITEVT/lpc11cx4-library/blob/master/lpc_chip_11cxx_lib/src/startup_LPC11xx.S#L126

you'll see the definition

```
#ifndef __START
#define __START _start
#endif
```

but `_start` is never defined, so if `__START` is not already defined, compilation fails.

It seems that only updated Makefiles (e.g. https://github.com/MITEVT/ltc-battery-management-system/blob/master/Makefile), with the following line:

`AS_DEFS = -D__STARTUP_CLEAR_BSS -D__START=main`

successfully compile, because the __START variable is already defined, and `#define __START _start`  is removed by the pre-processor and never executed during compilation, making compilation successful only on projects with the new Makefile.

**Comment by skoppula** [comment]
@ericponce @nsrango solution is replacing `_start` with `main` I think, but someone should check it over.

**Comment by ericponce** [comment]
lines should be

#ifndef __START
#error "No problem Start Function Designated"
#endfi
